# Generated by Django 5.1.5 on 2025-10-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0013_incidents_municipal_corporation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidents',
            name='incidentType',
            field=models.CharField(choices=[('Pothole/Road Damage', 'Pothole/Road Damage'), ('Water Pipe Burst', 'Water Pipe Burst'), ('Overflowing Trash Bins', 'Overflowing Trash Bins'), ('Illegal Dumping', 'Illegal Dumping'), ('Broken streetlights / lack of lighting', 'Broken streetlights / lack of lighting'), ('Voltage fluctuations in homes', 'Voltage fluctuations in homes'), ('Traffic signal not working', 'Traffic signal not working'), ('Overcrowded buses / irregular transport', 'Overcrowded buses / irregular transport'), ('Stray dogs / cattle on roads', 'Stray dogs / cattle on roads'), ('Domestic Violence', 'Domestic Violence'), ('Child Abuse', 'Child Abuse'), ('Sexual Harassment', 'Sexual Harassment'), ('Stalking', 'Stalking'), ('Human Trafficking', 'Human Trafficking'), ('Fire', 'Fire'), ('Theft', 'Theft'), ('Accident', 'Accident'), ('Injury', 'Injury'), ('Missing Persons', 'Missing Persons'), ('Natural Disaster', 'Natural Disaster'), ('Medical Emergency', 'Medical Emergency'), ('Other', 'Other')], default='Other', max_length=100),
        ),
    ]
