# Generated by Django 5.1.5 on 2025-10-09 15:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pothole_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotholeVideoAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='pothole_videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'avi', 'mov', 'mkv', 'webm'])])),
                ('processed_video', models.FileField(blank=True, null=True, upload_to='processed_videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='video_thumbnails/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processing_progress', models.IntegerField(default=0, help_text='Progress percentage 0-100')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('fps', models.FloatField(blank=True, null=True)),
                ('total_frames', models.IntegerField(blank=True, null=True)),
                ('frames_analyzed', models.IntegerField(default=0)),
                ('total_potholes_detected', models.IntegerField(default=0)),
                ('average_severity', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20, null=True)),
                ('max_severity', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20, null=True)),
                ('average_area_cm2', models.FloatField(blank=True, null=True)),
                ('average_depth_cm', models.FloatField(blank=True, null=True)),
                ('total_estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('route_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gps_data', models.JSONField(blank=True, help_text='GPS coordinates for video route', null=True)),
                ('timestamp_data', models.JSONField(blank=True, help_text='Pothole detections with timestamps', null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Pothole Video Analysis',
                'verbose_name_plural': 'Pothole Video Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoFrameDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_number', models.IntegerField()),
                ('timestamp_seconds', models.FloatField()),
                ('frame_image', models.ImageField(blank=True, null=True, upload_to='video_frames/')),
                ('width_cm', models.FloatField(blank=True, null=True)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('area_cm2', models.FloatField(blank=True, null=True)),
                ('depth_estimate', models.FloatField(blank=True, null=True)),
                ('perimeter_cm', models.FloatField(blank=True, null=True)),
                ('severity', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('impact_score', models.IntegerField(blank=True, null=True)),
                ('bbox_x', models.IntegerField(blank=True, null=True)),
                ('bbox_y', models.IntegerField(blank=True, null=True)),
                ('bbox_width', models.IntegerField(blank=True, null=True)),
                ('bbox_height', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frame_detections', to='pothole_analyzer.potholevideoanalysis')),
            ],
            options={
                'ordering': ['frame_number'],
                'unique_together': {('video_analysis', 'frame_number')},
            },
        ),
    ]
