# Generated by Django 5.1.5 on 2025-10-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pothole_analyzer', '0002_potholevideoanalysis_videoframedetection'),
    ]

    operations = [
        migrations.AddField(
            model_name='potholeanalysis',
            name='latitude',
            field=models.FloatField(blank=True, help_text='GPS latitude coordinate', null=True),
        ),
        migrations.AddField(
            model_name='potholeanalysis',
            name='location_accuracy',
            field=models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True),
        ),
        migrations.AddField(
            model_name='potholeanalysis',
            name='longitude',
            field=models.FloatField(blank=True, help_text='GPS longitude coordinate', null=True),
        ),
    ]
